authentication/urls.py
from django.urls import path
from authentication.views import login, logout

app_name = 'authentication'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

game_locker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls'))
]

main/urls.py
from django.urls import path
from main.views import show_main, create_item, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register, login_user, logout_user, get_item_json, add_item_ajax, create_item_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-item', create_item, name='create_item'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('get-item/', get_item_json, name='get_item_json'),
    path('create-ajax/', add_item_ajax, name='add_item_ajax'),
    path('create-flutter/', create_item_flutter, name="create_item_flutter"),
]

authentication/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255) 
    amount = models.IntegerField()
    description = models.TextField()
    price = models.IntegerField()
    genre = models.CharField(max_length=30)
    date_added = models.DateField(auto_now_add=True)

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "price", "amount", "genre", "description"]

authentication/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth import logout as auth_logout
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            auth_login(request, user)
            # Status login sukses.
            return JsonResponse({
                "username": user.username,
                "status": True,
                "message": "Login sukses!"
                # Tambahkan data lainnya jika ingin mengirim data ke Flutter.
            }, status=200)
        else:
            return JsonResponse({
                "status": False,
                "message": "Login gagal, akun dinonaktifkan."
            }, status=401)

    else:
        return JsonResponse({
            "status": False,
            "message": "Login gagal, periksa kembali email atau kata sandi."
        }, status=401)

@csrf_exempt
def logout(request):
    username = request.user.username

    try:
        auth_logout(request)
        return JsonResponse({
            "username": username,
            "status": True,
            "message": "Logout berhasil!"
        }, status=200)
    except:
        return JsonResponse({
        "status": False,
        "message": "Logout gagal."
        }, status=401)

main/views.py
import datetime
import json
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.core import serializers
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from main.forms import ItemForm
from main.models import Item

@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user=request.user)
    context = {
        'name': request.user.username,
        'class': 'PBP C',
        'items': items,
        'total_items': items.count(),
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

@csrf_exempt
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
        
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_item.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def get_item_json(request):
    data = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', data))

@csrf_exempt
def add_item_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        price = request.POST.get("price")
        amount = request.POST.get("amount")
        genre = request.POST.get("genre")
        description = request.POST.get("description")
        user = request.user

        new_product = Item(name=name, price=price, amount=amount, genre=genre, description=description, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def create_item_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            price = int(data["price"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_item.html
{% extends 'base.html' %} 

{% block meta %}
    <title>Create Item</title>
{% endblock meta %}

{% block content %}
<div class="container-fluid">
        <h1 style="color: #213555" class="fw-bold display-5">Add Item</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <table class="my-3">  
                {{ form.as_table }}
            </table>  
            <div class="">
                <button type="button submit" class="btn mb-3" style="background-color: #4F709C; color: white" value="Add Item">Add Item</button>
            </div>
        </form>
</div>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
<div class="container-fluid d-flex justify-content-center align-items-center min-vh-100">
    <div class="login p-3 border-100 rounded shadow-sm text-center" style="background-color: #D8C4B6">
        <h1 style="color: #213555" class="fw-bold display-5">Login</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="input-group my-3">
                <span class="input-group-text">Username</span>
                <input type="text" name="username" class="form-control" style="max-width: 300px" placeholder="Username">
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text">Password</span>
                <input type="password" name="password" class="form-control" style="max-width: 300px" placeholder="Password">
            </div>
            {% if messages %}
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            {% endif %}
            <button type="button submit" class="btn mb-3" style="background-color: #4F709C; color: white" value="Login">Login</button>
        </form>
        <p>Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a></p>
    </div>
</div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block meta %}
<title>Game Locker</title>
{% endblock meta %}

{% block content %}
<div class="container-fluid">
    <h1 class="fw-bold display-5" style="color: #213555">Game Locker</h1>
    <h5>Name: {{ name }}</h5>
    <h5>Class: {{ class }}</h5>
    {% if total_items == 0 or total_items == 1%}
        <p>You have saved {{total_items}} game in this app.</p>
    {% else %}
        <p>You have saved {{total_items}} games in this app.</p>
    {% endif %}
    <div id="item_cards" class="d-grid gap-2 d-flex flex-wrap justify-content-center justify-content-md-start"></div>

    <br />
    
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="name" name="name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="price" class="col-form-label">Price:</label>
                            <input type="number" class="form-control" id="price" name="price"></input>
                        </div>
                        <div class="mb-3">
                            <label for="amount" class="col-form-label">Amount:</label>
                            <input type="number" class="form-control" id="amount" name="amount"></input>
                        </div>
                        <div class="mb-3">
                            <label for="genre" class="col-form-label">Genre:</label>
                            <input type="text" class="form-control" id="genre" name="genre"></input>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn" style="background-color: #4F709C; color: white" id="button_add" data-bs-dismiss="modal">Add Product</button>
                    <button type="button" class="btn btn-danger" id="button_close" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <div class="d-grid gap-2 d-flex mb-3 justify-content-center justify-content-md-start">
        <a href="{% url 'main:create_item' %}" class="btn" style="background-color: #4F709C; color: white">Add New Item</a>
        <button type="button" class="btn" style="background-color: #4F709C; color: white" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product by AJAX</button>
        <a href="{% url 'main:logout' %}" class="btn btn-danger">Logout</a>
    </div>

    <h5>Last login: {{ last_login }}</h5>
</div>
<script>
    async function getItems() {
        return fetch("{% url 'main:get_item_json' %}").then((res) => res.json())
    }
    
    async function refreshItems() {
        document.getElementById("item_cards").innerHTML = ""
        const products = await getItems()
        let htmlString = ``
        products.forEach((item) => {
            htmlString += `<div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title fw-bold">${item.fields.name}</h5>
                    <p class="card-text">Rp${item.fields.price}</p>
                    <p class="card-text">${item.fields.amount}</p>
                    <p class="card-text">${item.fields.genre}</p>
                    <p class="card-text">${item.fields.description}</p>
                    <p class="card-text">${item.fields.date_added}</p>
                </div>
            </div>
            `
        })
        
        document.getElementById("item_cards").innerHTML = htmlString
    }

    refreshItems()

    function addItems() {
        fetch("{% url 'main:add_item_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshItems)

        resetModal()
        return false
    }
    
    function resetModal() {
        document.getElementById("form").reset()
    }
    
    document.getElementById("button_add").onclick = addItems
    document.getElementById("button_close").onclick = resetModal
</script>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  
<div class="container-fluid d-flex justify-content-center align-items-center min-vh-100">
    <div class="register p-3 border-100 rounded shadow-sm" style="background-color: #D8C4B6">
        <h1 class="fw-bold display-5 text-center" style="color: #213555">Register</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <table class="my-3">  
                {{ form.as_table }}
            </table>  
            {% if messages %}
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
            {% endif %}
            <div class="text-center">
                <button type="button submit" class="btn mb-3" style="background-color: #4F709C; color: white" value="Register">Register</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        {% block meta %}
        {% endblock meta %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>

    <body style="background-color: #FFF8F0;">
        {% block content %}
        {% endblock content %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    </body>
</html>